service:
  name: ignitecertificate

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'yarn'

provider:
  name: aws
  runtime: nodejs14.x
  region: sa-east-1

functions:
  hello:
    handler: src/functions/hello.handle
    events:
      - http:
          path: /hello
          method: get
          cors: true