service:
  name: ignitecertificate

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws

functions:
  hello:
    handler: src/functions/hello.handle
    events:
      - http:
          path: /hello
          method: get
          cors: true